type SENDING_MESSAGE = "SENDING_MESSAGE";
type DELETE_MESSAGE = "DELETE_MESSAGE";
type LOGIN = "LOGIN";
type LOGOUT = "LOGOUT";

export type ActionType = SENDING_MESSAGE | DELETE_MESSAGE | LOGIN | LOGOUT;